### ISSUE TITLE
Can we use M3Drop for allelic dropout 

### ISSUE THREAD

**Issue by Hemantcnaik** [tallulandrews/M3Drop#12]
Hello,

Thanks for the great tool. I have smart seq 2 sequenced data and have single cell rna seq allelic read counts(allele A and allele B) can I use M3drop remove the allelic dropout applying M3drop for each allelic read count file or combine allele A + allele B  remove the genes and filtered genes in allele A and allele B separatly.

Can you please comment on this it will be very helpfull. 

Thank you

**Comment by tallulandrews** [comment]
You'd probably want to apply to each allele separately and look at where there is / isn't overlap between allele A and allele B
