### ISSUE TITLE
Regarding Version 3.10.3 

### ISSUE THREAD

**Issue by AswinSSoman** [tallulandrews/M3Drop#6]
Hi,

Thanks for the great tool.

When I install the `M3Drop` package from github it install the version `3.10.3`, which doesn't seems to be working properly. But in bioconductor, `1.8.0` is the latest version and `1.9.3` is the developmental version. It would be really helpful if you could give some information regarding version `3.10.3`.

Best, 
Aswin

**Comment by tallulandrews** [comment]
Hi Aswin,

Version 3.10.3 is the same as the development version on bioconductor (1.9.3). And contains a second method "NBumi" which is tailored specifically for UMI-tagged data, which follows a pure negative binomial distribution, in contrast to Smartseq2/untagged data that is more similar to a zero-inflated negative binomial.

Best,
Tallulah
