### ISSUE TITLE
re SingleCellExperiment class and M3DropConvertData

### ISSUE THREAD

**Issue by haircell** [tallulandrews/M3Drop#8]
Hi,

I have a question please re `M3DropConverData` when used with `SingleCellExperiment`: 
The documentation for this function indicates that when used with SCE, it "uses "logcounts", which is assumed to be log-normalized, or if unavailable then "counts"." 

Does this mean that assay(s) under `SCE` labeled `normcounts` do not get used with `M3DropConvertData`? Typically `SCE` assays are labeled as `counts`, `normcounts`, and `logcounts` (these are the "suggested names" - https://bioconductor.org/packages/release/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html)

If I want `M3DropConvertData` to use my normalized counts from a different algorithm (I'm using SCnorm) that is not log-transformed, should I just rename it `counts`? Would it be possible to have `M3DropConvertData` recognize `normcounts` from `SCE`? 

Thank you!

**Comment by tallulandrews** [comment]
Most people/tools weren't using normcounts when I last updated the package. I will modify to use "normcounts" first for the next release. For the moment, the best option would be to extract the matrix yourself and use `M3DropConvertData(sce_obj@assays[["normcounts"]], is.log=FALSE, is.counts=FALSE)`. This will prevent M3Drop from doing anything except removing undetected genes.

**Comment by tallulandrews** [comment]
Support for normcounts is now available in the github version.
