### ISSUE TITLE
Is Depth-Adjusted Negative Binomial (DANB) model deprecated in your package?

### ISSUE THREAD

**Issue by MJ-Yang** [tallulandrews/M3Drop#9]
Hello, 

I am dealing with UMI-tagged data so I was thinking of using your DANB model.

However, I could no longer find functions related to DANB models in your newest release.

Are there any alternatives/suggestions to deal figure out highly variable genes in UMI data? 

Thanks,

MJ

**Comment by tallulandrews** [comment]
They should still be there. Which version are you using and where did you download it from?
The DANB methods are labelled as starting with "NBumi".
